name: 매일 경제뉴스 발송

on:
  schedule:
    - cron: '30 22 * * 0-5'  # 월~토 오전 7:30 KST (UTC 전날 22:30, 일~금)
    - cron: '40 6 * * 1-5'   # 월~금 오후 3:40 KST (UTC 당일 06:40)
  workflow_dispatch:          # 수동 실행 버튼

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4.2.2

      - name: Python 설치
        uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.11'

      - name: 메일 발송
        env:
          GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
          GMAIL_APP_PW: ${{ secrets.GMAIL_APP_PW }}
          TO_ADDRESS: ${{ secrets.TO_ADDRESS }}
        run: python daily_economic_news.py
